
%% Demo2: 
% Author : Zhibin Zhao
% Place  : Xi'an Jiaotong University
% Email  : zhibinzhao1993@gmail.com
% Date   : 2018.6
clc
clear all
close all
addpath(genpath(fileparts(mfilename('fullpath'))));
rng('default')
rng(36)
% The data were generated by NSF I/UCR Center on Intelligent Maintenance Systems
% (IMS) with support from Rexnord Corp. in Milwaukee, WI.
% Reference:
% Hai Qiu, Jay Lee, Jing Lin, ¡°Wavelet Filter-based Weak Signature Detection Method and
% its Application on Roller Bearing Prognostics¡±, Journal of Sound and Vibration, Volume
% 289, 2006, pages 1066-1090

% The data collected from 2nd_test, No:500 (early stage of the fault) and No:703 (middle stage of the fault)
% The sampling frequency is 20480Hz, the fault characteristic frequency of
% outer race is 236.4Hz
%% Load your own data
N = 8192;
load nasa_500.mat
Sig = x1(1: N);
t = (0: N-1) / Fs;
%% Perform the proposed method
Params.W_type     = 'multi-scale PMI';        % multi-scale PMI
Params.Fs         = Fs;                       % Fs is the sampling frequency
Params.F_Interval = [int8(F-20), int8(F+20)];   % F is the characteristic frequency
Params.K_s        = 0.2;
[y_HHLP, ~] = HHLP(Sig, Params);
[ yf, f ] = Hilbert_envelope( y_HHLP , Fs , 1);
figure(1)
subplot(311)
plot(t, Sig)
title('Original Signal')
xlabel('Time (s)')
ylabel('Amp (g)')
subplot(312)
plot(t, y_HHLP)
title('HHLP')
xlabel('Time (s)')
ylabel('Amp (g)')
subplot(313)
plot(f(1:800), yf(1:800))
title('SES')
xlabel('Frequency (Hz)')
ylabel('Amp (g^2)')
filename = ['results', filesep, sprintf('Demo2_Early_Stage.pdf')];
print(filename, '-dpdf');
%% Load your own data
load nasa_703.mat
Sig = x2(1: N);
t = (0: N-1) / Fs;
%% Perform the proposed method
Params.W_type     = 'multi-scale PMI';
Params.Fs         = Fs;                       % Fs is the sampling frequency
Params.F_Interval = [int8(F-20), int8(F+20)];   % F is the characteristic frequency
Params.K_s        = 0.05;
[y_HHLP, ~] = HHLP(Sig, Params);
[ yf, f ] = Hilbert_envelope( y_HHLP , Fs , 1);
figure(2)
subplot(311)
plot(t, Sig)
title('Original Signal')
xlabel('Time (s)')
ylabel('Amp (g)')
subplot(312)
plot(t, y_HHLP)
title('HHLP')
xlabel('Time (s)')
ylabel('Amp (g)')
subplot(313)
plot(f(1:800), yf(1:800))
title('SES')
xlabel('Frequency (Hz)')
ylabel('Amp (g^2)')
filename = ['results', filesep, sprintf('Demo2_Middle_Stage.pdf')];
print(filename, '-dpdf');
% If you feel our HHLP is useful for your research, please consider citing our paper:
% @article{zhao2019hierarchical,
%   title={Hierarchical hyper-Laplacian prior for weak fault feature enhancement},
%   author={Zhao, Zhibin and Wang, Shibin and An, Botao and Guo, Yanjie and Chen, Xuefeng},
%   journal={ISA transactions},
%   year={2019},
%   publisher={Elsevier}
% }